package com.example.myquizeapp;
public class QuestionAnswer {
    public static String question[]={
            "Which company owns the android?",
            "Which one is not the programming language?",
            "The VLSI was used in .......... generation computers.",
            "Which symbol is used to represent group of any characters?",
            "When was the CRAY-I super computer built?",
            "Which switch will be used in Dir to see a screenful contents of disk at a time?",
            "When was the P4 computer introduced?",
            "Which is not invalid user file name?",
            "The memory serves as a buffer between processor and memory is........",
            "Which is not valid alphabet for attribute setting?",
            "The memory which allocate space for DOS and application is called..........",
            "Which will not create a sub directory on disk?",
            "The data density of tape is measured in..........",
            "The command sorts the fragments of file and enhanced the performance of disk is.....",
            "Which directory can not be created by MD command?",
            "Which is the system software?",
            "The command allows you to show the status of disk.",
            "The most of the input devices consist .......... for signal conversion.",
            "The latest 16-bit Unicode can represent the .......... symbols.",
            "The system files are resides in the .......... after booting process.",
            "The break checking command is..........",
            "The full form of MICR is..........",
            "Which one is fast accessible?",
            "The command will display the history of operating system.",
            "The branch of science that deals with helping machine to solve complex problems like human fashion.",
            "The Highest digit symbol of hexadecimal is..........",
            "The data transfer rate of USB cable is measured in terms of .......... bit per second.",
            "Which is an internal command?",
            "The output device is used for meeting and conference.",
            "The system software which translates an instruction at a time from source program and execute it.",
            "The multi-user operating system is..........",
            "Which is not function of operating system?",
            "The software are made available free of charge on trial based software are called..........",
            "When was MS-Windows introduced?",
            "The second generation computer is..........",
            "Which is the backup storage device?",
            "The command is used to remove sub-directory which contains some files.",
            "The high speed and capable to support large number of devices is..........",
            "Which command is used to go to parent directory from its sub-directory?",
            "The microprocessor contains the millions of..........",
            "Which is the characteristic of computer?",
            "The term Gigabytes refers to..........",
            "The assembly language uses the..........",
            "The video display adapter does not support..........",
            "Which is not input device?",
            "The most popular keyboard type is..........",
            "The permanent memory which exhibits characteristics of RAM is..........",
            "Which is not true for speed of CPU?",
            "The command fixes the errors of disk.",
            "What will be the command if you want to copy ra.doc file that resides in the floppy disk into work sub-directory of hard-disk while you are in c-prompt. ",

    };

  public static String choices[][] = {
    {"Google", "Apple", "Nokia", "Samsung"},
    {"Java", "Kotlin", "Notepad", "Python"},
    {"First", "Second", "Third", "Fourth"},
    {"?", "#", "*", "@"},
    {"1960", "1976", "1980", "1995"},
    {"/p", "/.w", "/s", "/b"},
    {"1980 ", "1990", "2000", "2004"},
    {"Raj.exe", "Ram.txt", "Kumar.sys", "Rajan.com"},
    {"Virtual memory", "Flash memory", "Cache memory", "RAM"},
    {"R", "S", "H", "C"},
    {"Expanded memory", "Cache memory", "Virtual memory", "Conventional memory"},
    {"Mkdir", "Md", "Chdir", "All of the above"},
    {"Bits per inch", "Bytes per inch ", "Record per inch", "None"},
    {"Scandisk", "Chkdsk", "Defrag", "Sys"},
    {"Sub directory", "Root Directory", "Child Directory", "None"},
    {"Operating system", "Compiler", "Utilities", "All of the above"},
    {"Vol", "Diskcomp", "Chkdsk", "Defrag"},
    {"Encoder", "Decoder", "Modem", "None"},
    {"256", "32567", "40000", "65536"},
    {"ROM", "Processor", "RAM", "Hard disk"},
    {"Ctrl+C", "Ctrl+B", "Ctrl+Z", "All of the above"},
    {"Magnetic Ink Character Reader", "Magnetic Ink Character Recognition", "Magnetic Ink Coding Reader", "Magnet Ink Character Recognition"},
    {"RAM", "Register", "Hard disk", "Tape"},
    {"Chkdsk", "Mem", "Vol", "Ver"},
    {"Generic Science", "Artificial Intelligence", "Computer Science", "All of the above"},
    {"9", "16", "F", "E"},
    {"Mega", "Kilo", "Giga", "Milli"},
    {"Label", "Mem", "Path", "Sys"},
    {"Monitor", "Printer", "Plotter", "LCD projector"},
    {"Translator", "Compiler", "Interpreter", "Assembler"},
    {"Linux", "Unix", "Windows 2000", "All of the above"},
    {"Managing application", "Detecting errors", "Managing memory and files", "Detecting virus"},
    {"Firmware", "Shareware", "Application software", "System Software"},
    {"1975", "1980", "1985", "1995"},
    {"IBM-702", "IBM-1400", "IBM system/360", "IBM system/370"},
    {"ROM", "RAM", "Floppy", "Register"},
    {"RD", "RMDir", "Deltree", "Erase"},
    {"USB", "Parallel", "Serial", "SCSI"},
    {"Cd", "CD/", "Cd..", "None"},
    {"Registers", "Transistors", "Capacitors", "All of the above"},
    {"Accuracy", "Reliability", "Speed", "All of the above"},
    {"1024 bytes", "1024 kilobytes", "1024 megabytes", "1024 megabits"},
    {"Machine code", "Rough code", "Human code", "Mnemonic code"},
    {"4-bit", "8-bit", "12-bit", "16-bit"},
    {"Digitizer", "Data glove", "Sensors", "Voice synthesis"},
    {"QWERTY", "PQRSTY", "Ergonomic", "IBM"},
    {"Cache memory", "Virtual memory", "Base memory", "Internal memory"},
    {"System Clock rate", "Bus width", "Word length", "Price of CPU"},
    {"ErrorFix", "Scandisk", "Chkdsk", "Defrag"},
    {"Copy c:/ra.doc  a:/work", "Copy a:/ra.doc  c:/work", "Copy ra.doc  c:/work", "Copy c:/work  a:/ra.doc"}

  };



  public static String correctAnswers[] = {
          "Google",
          "Notepad",
          "Fourth",
          "*",
          "1976",
          "/p",
          "2000",
          "Ram.txt",
          "Cache memory",
          "C",
          "Conventional memory",
          "Chdir",
          "Bits per inch",
          "Defrag",
          "Root Directory",
          "All of the above",
          "Chkdsk",
          "Encoder",
          "65536",
          "RAM",
          "Ctrl+C",
          "Magnetic Ink Character Recognition",
          "Register",
          "Ver",
          "Artificial Intelligence",
          "F",
          "Mega",
          "Path",
          "LCD projector",
          "Interpreter",
          "All of the above",
          "Detecting virus",
          "Shareware",
          "1985",
          "IBM-1400",
          "Floppy",
          "Deltree",
          "USB",
          "Cd..",
          "Transistors",
          "All of the above",
          "1024 megabytes",
          "Mnemonic code",
          "12-bit",
          "Voice synthesis",
          "QWERTY",
          "Virtual memory",
          "Price of CPU",
          "Scandisk",
          "Copy a:/ra.doc  c:/work"

  };
}
